sudo: required
services:
  - docker
before_install:
  - docker build -t reacttest -f ./client/Dockerfile.dev ./client
script: 
  - docker run -e CI=true reacttest npm test

after_success:
  - docker build -t sarathy1127/multi-client ./client
  - docker build -t sarathy1127/multi-nginx ./nginx
  - docker build -t sarathy1127/multi-server ./server
  - docker build -t sarathy1127/multi-worker ./worker
 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sarathy1127/multi-client
  - docker push sarathy1127/multi-nginx
  - docker push sarathy1127/multi-server
  - docker push sarathy1127/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multi-docker-env
  bucker_name: elasticbeanstalk-us-east-1-413932034466
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY